# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql 
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/var/lib/mysql/csvs
    restart: always 
    environment:
      MYSQL_DATABASE: veggietales-db 
      MYSQL_PASSWORD: veggietales 
      MYSQL_ROOT_PASSWORD: veggietales-root 
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql  
  
volumes:
  my-db:
    driver_opts: 
          type: none 
          device: ${PWD}/data  
          o: bind 

